"""
Deal domain keywords — independent flat lists from Vendor List sheet.
Columns A (Vendor), B (Product), C (Process), D (Technology) are unrelated.
Used to enrich deal search queries for any company scan.
"""

PRODUCT_KEYWORDS: list[str] = ['AWS', 'Adobe', 'Aruba', 'Azure', 'Cisco', 'Cloudera Enterprise platform', 'Dell EMC', 'Dynamics 365', 'Exchange', 'Google Apps', 'Guidewire', 'IBM Watson', 'Infor', 'Lync', 'Microsoft CRM', 'Microsoft OneNote', 'NetApp', 'NetSuite', 'Office 365', 'Oracle', 'Oracle Exadata', 'PeopleSoft', 'Red Hat', 'SAP', 'SAP HANA', 'SAP Hybris', 'Salesforce.com', 'ServiceNow', 'Sharepoint', 'SuccessFactor', 'UltiPro', 'Windows', 'Workday']

PROCESS_KEYWORDS: list[str] = ['ATM Management', 'Accident & Health Insurance', 'Account Administration', 'Account Payable', 'Account Receivable', 'Actuarial Services', 'Administrative Services', 'Affordable Care Act', 'Air Cargo', 'Air Traffic Control', 'Airline Ticketing', 'Airport Management', 'Auto Insurance', 'Baggage Handling', 'Benefits Administration', 'Benefits Management', 'Billing Services', 'Budgeting', 'Business Process Engineering', 'Business Process Management', 'Card Processing', 'Case Management', 'Change Management', 'Claims', 'Claims (Health)', 'Claims (Non-Health)', 'Clinical Data Management', 'Collection Services', 'Compensation Management', 'Contact Center', 'Contract Management', 'Core Banking', 'Core HR', 'Custody Services', 'Customer Care Automation', 'Customer Experience (CX)', 'Customer Portal', 'Customer Relationship Management', 'Customer Service', 'Defense Fee Collection', 'Digital Marketing', 'Disease Management', 'Educational Services', 'Electronic Health Record', 'Employee Self-Service', 'Employment Services', 'Energy Management', 'Enterprise Asset Management', 'Expense Reimbursement', 'Finance & Accounting', 'Financial Audit', 'Fleet Scheduling/Planning', 'Fund Accounting', 'Fund Administration', 'General Ledger', 'Health Information Management System', 'Housing Management System', 'Human Resource Management', 'Inventory Management', 'Learning', 'Legal', 'Life & Annuity Insurance', 'Loans (Banking)', 'Manufacturing', 'Mortgage Processing', 'Online banking', 'Order Management', 'Order-to-Cash', 'P&C Insurance', 'Passenger Services', 'Payment Processing', 'Payroll', 'Pension Administration', 'Pension Payments', 'Point of Sale', 'Policing', 'Policy Administration', 'Procure to Pay', 'Procurement', 'Product Cost Management', 'Product Life-Cycle Management', 'Production Planning & Scheduling', 'Project Management', 'Property Management System', 'Record to Report', 'Recovery Management Services', 'Recruitment', 'Registry of Motor Vehicles', 'Reinsurance', 'Research & Development', 'Retail Automation', 'Risk Management', 'Sales and Marketing', 'School Management System', 'School Nutrition Solution', 'Service Support', 'Smart Grid', 'Smart Meter', 'Sourcing', 'Student Financial Aid', 'Student Management System', 'Subrogation (Insurance)', 'Supplier Management', 'Supply Chain Planning', 'Talent Management', 'Tax Management', 'Tax Reporting', 'Technical Support', 'Ticketing System (Non-Airline)', 'Toll System', 'Traffic Management', 'Traffic Surveillance', 'Transportation Management Solution', 'Travel Management', 'Underwriting', 'Voting/Election', 'Welfare Benefits', 'Workforce Management', 'Workforce Performance Management', 'e-commerce']

TECHNOLOGY_KEYWORDS: list[str] = ['2G', '3G', '4G LTE - A', '5G', 'Agile Development', 'Android', 'Anti-Fraud', 'Anti-Money Laundering', 'Application Development', 'Application Performance Management', 'Application Portfolio Management', 'Application Testing', 'Artificial Intelligence', 'Audio Conferencing', 'Automation', 'Azure', 'BMC', 'BYOD', 'Big Data', 'Biometrics', 'Blackberry', 'Blockchain', 'Bluemix', 'Business Analytics', 'Business Intelligence', 'CRM', 'Chatbot', 'Cloud (Hybrid)', 'Cloud (Private)', 'Cloud (Public)', 'Colocation', 'Compliance', 'Content Analytics', 'Content Management', 'Converged Services', 'Cybersecurity', 'Data Center Consolidation', 'Data Center Migration', 'Data Integration', 'Data Mining', 'Data Visualization', 'Data Warehouse Appliance', 'Data Warehousing', 'Data-Center', 'Decision Analytics', 'Desktop', 'Desktop Virtualization', 'Digital Asset Management', 'Digital Services', 'Digital Transformation', 'Digital Twin', 'Digital workplace', 'Disaster Recovery', 'Document Management', 'ERP', 'Email Security', 'Endpoint Security', 'Enterprise Manufacturing Intelligence', 'Ethernet', 'Fiber Optic Network', 'Financial Analytics', 'Firewall', 'Fixed Telephony', 'Fraud Detection', 'GSM', 'Geo-Spatial', 'HR Analytics', 'Hadoop', 'Health Analytics', 'High Performance Computing', 'Hyperconverged Infrastructure', 'IP MPLS', 'IP Telephony', 'IP Transit', 'IP VPN', 'IP-based Core Network', 'IT Analytics', 'IT Asset Management', 'IT Operations Management', 'IT Service Desk', 'IT Service Management', 'IaaS', 'IoT', 'Learning Management System', 'Legacy', 'Linux', 'Local Area Network', 'MPLS', 'Mainframe', 'Managed Data Service', 'Managed Security', 'Marketing Analytics', 'Mobile', 'Mobile Advertising', 'Mobile Application Development', 'Mobile Applications', 'Mobile Broadband', 'Mobile Commerce', 'Mobile Payments', 'Mobile Telephony Services', 'Mobile Testing', 'Multi-cloud', 'Natural Language Processing', 'Network', 'Network Function Virtualization', 'Network Security', 'Network Upgrade', 'OSS/BSS', 'Open Source', 'OpenStack', 'Operational Technology', 'Optical Transport Network', 'PaaS', 'Performance Analytics', 'Predictive Analytics', 'Prescriptive Analytics', 'Quality Assurance', 'RPA', 'Radio Base Stations', 'Real-Time', 'Retail Analytics', 'Risk Management', 'SaaS', 'Security', 'Security Equipment', 'Service Oriented Architecture', 'Small Cell Technology', 'Smart City', 'Smart Phones', 'Social', 'Software Defined Data-center', 'Software Defined Network', 'Spend Analytics', 'Storage', 'Supply Chain Analytics', 'Tablets', 'Transformation', 'Unified Communications', 'Unix', 'VMware', 'VPN', 'Video Conferencing', 'Virtual Private LAN', 'Virtualization', 'Voice Over LTE', 'Voice over Internet Protocol', 'Wide Area Network', 'Windows Mobile', 'Wireless LAN', 'iOS']

# Combined — all terms that signal an IT deal domain
ALL_DEAL_KEYWORDS: list[str] = list(dict.fromkeys(
    PRODUCT_KEYWORDS + PROCESS_KEYWORDS + TECHNOLOGY_KEYWORDS
))
