"""IT Deals Intelligence API — FastAPI with SSE streaming."""

import asyncio
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from config_loader import ScraperConfig
from pipeline_stream import stream_pipeline, extract_from_cached_urls, load_url_cache, save_url_cache

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="IT Deals Intelligence API", version="1.0.0")

ALLOWED_ORIGINS = os.getenv(
    "ALLOWED_ORIGINS",
    "http://localhost:3000,https://localhost:3000"
).split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response Models ─────────────────────────────────────────────────

class ScrapeRequest(BaseModel):
    company_name: str = Field(..., min_length=1)
    company_aliases: list[str] = Field(default_factory=list)
    domain: str = Field(..., min_length=3)
    secondary_domains: list[str] = Field(default_factory=list)
    linkedin_url: str = Field(default="")
    stock_ticker: str | None = None
    exchange: str | None = None
    industry_sector: str = ""
    hq_country: str = ""
    hq_city: str = ""
    search_year_range: dict[str, int] = Field(default={"start": 2020, "end": 2025})
    known_sources: list[str] = Field(default_factory=list)
    known_deals_to_skip: list[str] = Field(default_factory=list)
    focus_deal_types: list[str] = Field(default_factory=list)
    min_deal_value_usd_million: float | None = None
    run_linkedin: bool = False
    batch_size: int = Field(default=5, ge=1, le=20)


def _request_to_config(req: ScrapeRequest) -> ScraperConfig:
    return ScraperConfig(
        company_name=req.company_name,
        company_aliases=req.company_aliases,
        domain=req.domain,
        secondary_domains=req.secondary_domains,
        linkedin_url=req.linkedin_url,
        stock_ticker=req.stock_ticker,
        exchange=req.exchange,
        industry_sector=req.industry_sector,
        hq_country=req.hq_country,
        hq_city=req.hq_city,
        search_year_range=req.search_year_range,
        known_sources=req.known_sources,
        known_deals_to_skip=req.known_deals_to_skip,
        focus_deal_types=req.focus_deal_types or [
            "ERP","CRM","HCM","SCM","cloud_migration","managed_services",
            "cybersecurity","digital_transformation","infrastructure",
            "analytics","AI_ML","outsourcing","SaaS","SI_contract"
        ],
        min_deal_value_usd_million=req.min_deal_value_usd_million,
        output_dir="/tmp/deals/",
        run_linkedin=req.run_linkedin,
        run_pdf_extraction=True,
        use_proxies=False,
        proxy_pool=[],
        notify_email=None,
    )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    keys = {
        "GOOGLE_AI_API_KEY": bool(os.getenv("GOOGLE_AI_API_KEY")),
        "ANTHROPIC_API_KEY": bool(os.getenv("ANTHROPIC_API_KEY")),
        "PARALLEL_API_KEY":  bool(os.getenv("PARALLEL_API_KEY")),
    }
    return {"status": "ok", "service": "it-deals-api", "v": "2.1.0", "env": keys}


@app.get("/api/usage")
async def usage_summary():
    """Aggregate Gemini API usage (calls, tokens, cost) by module, from the
    in-memory usage log. Resets on deploy/restart — see usage_logger.py."""
    from usage_logger import get_usage_summary
    return get_usage_summary()


@app.get("/api/usage/recent")
async def usage_recent(limit: int = 200):
    """Most recent N logged Gemini calls, newest last."""
    from usage_logger import get_recent_usage
    return {"entries": get_recent_usage(limit)}


@app.get("/api/reports")
async def reports_list(module: str = "", limit: int = 100):
    """List completed reports (target, summary, cost) — includes reports
    generated by ANY caller, not just this browser's own localStorage,
    so a direct API/curl call still shows up in the frontend's history."""
    from report_store import list_reports
    return {"reports": list_reports(module, limit)}


@app.get("/api/reports/{run_id}")
async def reports_get_one(run_id: str):
    """Full report record, including result data — lets ANY client (not just
    the browser that originally streamed it) open a report for full detail."""
    from report_store import get_report
    report = get_report(run_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@app.delete("/api/reports/{run_id}")
async def reports_delete_one(run_id: str):
    from report_store import delete_report
    delete_report(run_id)
    return {"ok": True}


@app.delete("/api/reports")
async def reports_clear(module: str = ""):
    from report_store import clear_reports
    clear_reports(module)
    return {"ok": True}


@app.post("/api/scrape")
async def scrape(req: ScrapeRequest):
    """Stream deal results via SSE. Each event is a JSON object."""
    config = _request_to_config(req)

    async def event_stream():
        try:
            async for event in stream_pipeline(config, batch_size=req.batch_size):
                yield f"data: {json.dumps(event)}\n\n"
        except Exception as e:
            logger.error(f"Pipeline error: {e}", exc_info=True)
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


class ReExtractRequest(BaseModel):
    company_name: str
    urls: list[str] = Field(default_factory=list)
    batch_size: int = Field(default=5, ge=1, le=20)
    # Full company config needed for extraction context
    company_aliases: list[str] = Field(default_factory=list)
    domain: str = ""
    focus_deal_types: list[str] = Field(default_factory=list)
    min_deal_value_usd_million: float | None = None


@app.get("/api/cached-urls/{company_name}")
async def get_cached_urls(company_name: str):
    """Return cached URLs for a company (discovered in last 48h)."""
    urls = load_url_cache(company_name)
    if urls is None:
        raise HTTPException(status_code=404, detail=f"No cached URLs for '{company_name}' (or cache expired)")
    return {"company_name": company_name, "url_count": len(urls), "urls": urls}


@app.post("/api/extract")
async def extract(req: ReExtractRequest):
    """Re-run extraction on a provided list of URLs — skips search phase."""
    # Build minimal config for extraction context
    config = ScraperConfig(
        company_name=req.company_name,
        company_aliases=req.company_aliases,
        domain=req.domain or f"{req.company_name.lower().replace(' ', '')}.com",
        secondary_domains=[],
        linkedin_url="",
        stock_ticker=None,
        exchange=None,
        industry_sector="",
        hq_country="",
        hq_city="",
        search_year_range={"start": 2020, "end": 2025},
        known_sources=[],
        known_deals_to_skip=[],
        focus_deal_types=req.focus_deal_types or [
            "ERP","CRM","HCM","SCM","cloud_migration","managed_services",
            "cybersecurity","digital_transformation","infrastructure",
            "analytics","AI_ML","outsourcing","SaaS","SI_contract"
        ],
        min_deal_value_usd_million=req.min_deal_value_usd_million,
        output_dir="/tmp/deals/",
        run_linkedin=False,
        run_pdf_extraction=True,
        use_proxies=False,
        proxy_pool=[],
        notify_email=None,
    )

    # Use provided URLs or fall back to cache
    urls = req.urls
    if not urls:
        cached = load_url_cache(req.company_name)
        if not cached:
            raise HTTPException(status_code=404, detail="No URLs provided and no cache found for this company.")
        urls = cached

    async def event_stream():
        try:
            async for event in extract_from_cached_urls(config, urls, batch_size=req.batch_size):
                yield f"data: {json.dumps(event)}\n\n"
        except Exception as e:
            logger.error(f"Extract error: {e}", exc_info=True)
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )



# ── Tech Stack Finder ────────────────────────────────────────────────────────

class TechStackInput(BaseModel):
    company_name: str
    domain: str
    linkedin_url: str = ""
    focus_categories: list[str] = Field(default_factory=list)
    focus_vendors: list[str] = Field(default_factory=list)

class TechStackRequest(BaseModel):
    inputs: list[TechStackInput] = Field(..., min_length=1, max_length=20)


@app.post("/api/tech-stack")
async def tech_stack(req: TechStackRequest):
    """SSE stream: technographic profile per company."""
    from tech_stack_pipeline import find_tech_stack, TECH_STACK_FIELDS
    from usage_logger import new_run_id, get_usage_by_run

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set on server."})
            return

        run_id = new_run_id()
        yield _sse({"type": "progress", "message": f"🚀 Scanning tech stack for {len(req.inputs)} companies…"})

        results: list[dict] = []
        row_index = 0

        # Saving is done in `finally` (not after the loop) so a report is still
        # recorded with whatever partial results exist if the caller disconnects
        # mid-scan — e.g. a direct API/curl/automation call whose timeout is
        # shorter than the full multi-company scan. Without this, the client's
        # early disconnect raises GeneratorExit inside the loop above and the
        # code after it never runs, silently dropping the report entirely.
        try:
            for i, inp in enumerate(req.inputs):
                yield _sse({"type": "heartbeat", "message": f"🔍 Company {i+1}/{len(req.inputs)}: {inp.company_name}"})
                try:
                    async for event in find_tech_stack(
                        company_name=inp.company_name,
                        domain=inp.domain,
                        linkedin_url=inp.linkedin_url,
                        focus_categories=inp.focus_categories,
                        focus_vendors=inp.focus_vendors,
                        run_id=run_id,
                    ):
                        if event["type"] == "row_done":
                            results.append(event["row"])
                            yield _sse({"type": "row", "row": event["row"], "index": row_index})
                            row_index += 1
                        else:
                            yield _sse(event)
                except Exception as e:
                    logger.error(f"Tech stack error for {inp.company_name}: {e}", exc_info=True)
                    yield _sse({"type": "heartbeat", "message": f"⚠️ Error for {inp.company_name}: {e}"})
        finally:
            ts_usage = get_usage_by_run(run_id)
            from report_store import save_report
            save_report(run_id, "tech_stack_finder", ", ".join(i.company_name for i in req.inputs),
                        f"{len(results)} tools found", ts_usage,
                        data={"companies": [i.company_name for i in req.inputs], "rows": results})
        yield _sse({"type": "complete", "results": results, "total": len(results), "usage": ts_usage, "run_id": run_id})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── Enrichment Task ───────────────────────────────────────────────────────────

class EnrichInput(BaseModel):
    company_name: str
    domain: str
    linkedin_url: str = ""
    focus_tech: list[str] = Field(default_factory=list)
    focus_vendor: list[str] = Field(default_factory=list)

class SchemaField(BaseModel):
    key: str
    label: str
    type: str = "string"          # string | number | date | boolean
    description: str = ""

class EnrichTaskRequest(BaseModel):
    goal: str = Field(..., min_length=10)
    schema_fields: list[SchemaField] = Field(..., min_length=1)
    inputs: list[EnrichInput] = Field(..., min_length=1, max_length=50)


@app.post("/api/enrich-task")
async def enrich_task(req: EnrichTaskRequest):
    """SSE stream: Gemini + Google Search Grounding → deal extraction."""
    from enrich_pipeline import enrich_company
    from usage_logger import new_run_id, get_usage_by_run

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set on server."})
            return

        run_id = new_run_id()
        schema_fields = [f.model_dump() for f in req.schema_fields]

        yield _sse({"type": "progress", "message": f"🚀 Starting enrichment for {len(req.inputs)} companies…"})

        results: list[dict] = []

        deal_index = 0  # global row counter across all companies

        # Saving is done in `finally` (not after the loop) so a report is still
        # recorded with whatever partial results exist if the caller disconnects
        # mid-scan — e.g. a direct API/curl/automation call whose timeout is
        # shorter than the full multi-company scan. Without this, the client's
        # early disconnect raises GeneratorExit inside the loop above and the
        # code after it never runs, silently dropping the report entirely.
        try:
            for i, inp in enumerate(req.inputs):
                yield _sse({"type": "heartbeat", "message": f"🔍 Company {i+1}/{len(req.inputs)}: {inp.company_name}"})

                company_deals: list[dict] = []

                try:
                    async for event in enrich_company(
                        company_name=inp.company_name,
                        domain=inp.domain,
                        goal=req.goal,
                        schema_fields=schema_fields,
                        linkedin_url=inp.linkedin_url,
                        focus_tech=inp.focus_tech or [],
                        focus_vendor=inp.focus_vendor or [],
                        run_id=run_id,
                    ):
                        if event["type"] == "row_done":
                            deal_row = event["row"]
                            company_deals.append(deal_row)
                            results.append(deal_row)
                            yield _sse({"type": "row", "row": deal_row, "index": deal_index, "total": None})
                            deal_index += 1
                        else:
                            yield _sse(event)
                except Exception as e:
                    logger.error(f"Enrich pipeline error for {inp.company_name}: {e}", exc_info=True)
                    # emit a no_result row so frontend doesn't hang
                    fallback = {"company_name": inp.company_name, "domain": inp.domain, "_status": "error"}
                    for f in req.schema_fields:
                        fallback[f.key] = ""
                    results.append(fallback)
                    yield _sse({"type": "row", "row": fallback, "index": deal_index, "total": None})
                    deal_index += 1

                yield _sse({"type": "heartbeat", "message": f"✅ {inp.company_name}: {len(company_deals)} deals found"})
        finally:
            succeeded = sum(1 for r in results if r.get("_status") == "ok")
            deal_usage = get_usage_by_run(run_id)
            from report_store import save_report
            save_report(run_id, "it_deal_finder", ", ".join(i.company_name for i in req.inputs),
                        f"{succeeded}/{len(results)} deals found", deal_usage,
                        data={"companies": [i.company_name for i in req.inputs], "rows": results})
        yield _sse({
            "type": "complete",
            "results": results,
            "total": len(results),
            "succeeded": succeeded,
            "usage": deal_usage,
            "run_id": run_id,
        })

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


@app.get("/api/fetch-test")
async def fetch_test(url: str = "https://m.economictimes.com/industry/banking/finance/banking/hdfc-bank-signs-multi-year-data-and-technology-deal-with-refinitiv/articleshow/94349454.cms"):
    """Quick test: fetch one URL via Jina Reader and show result."""
    from website_router import fetch_via_jina_reader
    from nlp_extractor import is_deal_relevant
    import asyncio
    try:
        result = await asyncio.wait_for(fetch_via_jina_reader(url), timeout=25)
        if result is None:
            return {"status": "failed", "url": url, "reason": "Jina returned None"}
        text, _ = result
        return {
            "status": "ok",
            "url": url,
            "chars": len(text),
            "words": len(text.split()),
            "preview": text[:500],
            "is_deal_relevant": is_deal_relevant(text, ["HDFC Bank"], []),
        }
    except asyncio.TimeoutError:
        return {"status": "timeout", "url": url}
    except Exception as e:
        return {"status": "error", "url": url, "error": str(e)}


@app.get("/api/debug")
async def debug(company: str = "HDFC Bank"):
    """
    Full pipeline diagnostic.
    Returns: env vars, discovered URLs, per-URL fetch result, per-URL extraction result.
    Hit: /api/debug?company=HDFC+Bank
    """
    import asyncio
    from search_engine import _jina_search, JINA_KEY, QUERY_TEMPLATES_CUSTOMER
    from website_router import fetch_via_jina_reader, classify_url
    from nlp_extractor import is_deal_relevant, build_deal_record, NON_DEAL_DISQUALIFIERS, DEAL_ACTION_PHRASES

    year = 2025
    out: dict = {
        "company": company,
        "env": {},
        "queries": [],
        "urls_discovered": [],
        "url_results": [],
    }

    # ── Env check ─────────────────────────────────────────────────────────────
    out["env"] = {
        "JINA_KEY_set": bool(JINA_KEY),
        "JINA_KEY_prefix": JINA_KEY[:12] + "..." if JINA_KEY else None,
    }

    # ── Run 1 query only (keep under 30s Render timeout) ─────────────────────
    q = QUERY_TEMPLATES_CUSTOMER[0].format(company=company, year=year)
    out["queries"].append(q)
    try:
        urls = await asyncio.wait_for(_jina_search(q), timeout=10)
        out["urls_discovered"] = [{"url": u} for u in urls[:8]]
    except Exception as e:
        out["urls_discovered"] = [{"error": str(e)}]
        urls = []

    # Skip social, take first 3 real URLs
    _SKIP = {"linkedin.com","facebook.com","instagram.com","twitter.com","x.com","youtube.com","danelfin.com"}
    from urllib.parse import urlparse as _up
    unique_urls = [u for u in urls if not any(_up(u).netloc.lstrip("www.").endswith(s) for s in _SKIP)][:3]

    # ── Fetch + extract each URL (parallel) ───────────────────────────────────
    async def _probe(url: str) -> dict:
        entry: dict = {"url": url}
        try:
            result = await asyncio.wait_for(fetch_via_jina_reader(url), timeout=10)
            if result is None:
                entry["fetch"] = "empty"
            else:
                text, _ = result
                entry["fetch"] = "ok"
                entry["chars"] = len(text)
                entry["preview"] = text[:200]
                entry["relevant"] = is_deal_relevant(text, [company], [])
                if entry["relevant"]:
                    deal = build_deal_record(text=text, url=url, source_type="news_article",
                                            company_name=company, company_names=[company], soup=None)
                    entry["deal"] = deal
                else:
                    tl = text.lower()
                    entry["disq"] = [d for d in NON_DEAL_DISQUALIFIERS if d in tl]
                    entry["phrases"] = [p for p in DEAL_ACTION_PHRASES if p in tl][:5]
                    entry["company_found"] = company.lower() in tl
        except asyncio.TimeoutError:
            entry["fetch"] = "timeout"
        except Exception as e:
            entry["fetch"] = f"error: {e}"
        return entry

    out["url_results"] = await asyncio.gather(*[_probe(u) for u in unique_urls])
    return out


@app.get("/api/debug-enrich")
async def debug_enrich():
    """Diagnose enrichment: check env keys and test Gemini."""
    google_key = os.getenv("GOOGLE_AI_API_KEY", "")

    out: dict = {
        "env": {
            "GOOGLE_AI_API_KEY": "set" if google_key else "MISSING",
        },
        "gemini_test": "skipped — key missing",
    }

    if google_key:
        def _test_gemini():
            from google import genai
            from google.genai import types
            client = genai.Client(api_key=google_key)
            resp = client.models.generate_content(
                model="gemini-2.5-flash",
                contents='Return ONLY this JSON array: [{"ok": true}]',
                config=types.GenerateContentConfig(temperature=0, max_output_tokens=50),
            )
            return resp.text or ""
        try:
            result = await asyncio.wait_for(asyncio.to_thread(_test_gemini), timeout=30)
            out["gemini_test"] = result
        except Exception as e:
            out["gemini_test"] = f"ERROR: {e}"

    return out


@app.get("/api/debug-gemini-search")
async def debug_gemini_search(company: str = "Daimler Truck North America", full_prompt: bool = False):
    """Test Gemini with Google Search Grounding. full_prompt=true uses the real pipeline prompt."""
    google_key = os.getenv("GOOGLE_AI_API_KEY", "")
    if not google_key:
        return {"error": "GOOGLE_AI_API_KEY not set"}

    def _run():
        from google import genai
        from google.genai import types
        client = genai.Client(api_key=google_key)
        if full_prompt:
            from enrich_pipeline import _build_prompts
            prompts = _build_prompts(company, "", "", [], [])
            prompt = prompts[0]   # use first call prompt for quick test
            max_tok = 16384
        else:
            prompt = (
                f'Find 3 recent IT technology deals for {company}. '
                f'Return ONLY a JSON array: [{{"vendor":"..","deal_type":"..","date_signed":"..","description":".."}}]'
            )
            max_tok = 2048
        resp = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                tools=[types.Tool(google_search=types.GoogleSearch())],
                temperature=0.1,
                max_output_tokens=max_tok,
            ),
        )
        # Try .text, fall back to parts
        try:
            text = resp.text or ""
        except Exception:
            text = ""
            try:
                for part in resp.candidates[0].content.parts:
                    if hasattr(part, "text") and part.text:
                        text += part.text
            except Exception:
                pass
        finish = str(resp.candidates[0].finish_reason) if resp.candidates else "unknown"
        return text, finish

    try:
        raw, finish = await asyncio.wait_for(asyncio.to_thread(_run), timeout=180)
        import re as _re
        has_array = bool(_re.search(r"\[.*?\]", raw, _re.DOTALL))
        return {
            "company": company,
            "full_prompt": full_prompt,
            "finish_reason": finish,
            "chars": len(raw),
            "has_json_array": has_array,
            "preview": raw[:1200],
            "tail": raw[-600:] if len(raw) > 1200 else "",
        }
    except asyncio.TimeoutError:
        return {"error": "timeout after 60s"}
    except Exception as e:
        return {"error": str(e)}


@app.get("/api/debug-tech-stack")
async def debug_tech_stack(company: str = "Kubota North America", call_num: int = 1):
    """Test one tech stack Gemini call. call_num=1,2,3."""
    google_key = os.getenv("GOOGLE_AI_API_KEY", "")
    if not google_key:
        return {"error": "GOOGLE_AI_API_KEY not set"}

    def _run():
        from google import genai
        from google.genai import types
        from tech_stack_pipeline import _build_tech_stack_prompt, _gemini_tech_stack_sync
        prompt = _build_tech_stack_prompt(company, "", "", [], [], call_num)
        result = _gemini_tech_stack_sync(prompt, company)
        return result

    def _run_raw():
        from google import genai
        from google.genai import types
        from tech_stack_pipeline import _build_tech_stack_prompt
        prompt = _build_tech_stack_prompt(company, "", "", [], [], call_num)
        client = genai.Client(api_key=google_key)
        resp = client.models.generate_content(
            model="gemini-2.5-flash", contents=prompt,
            config=types.GenerateContentConfig(
                tools=[types.Tool(google_search=types.GoogleSearch())],
                temperature=0.1, max_output_tokens=65536,
            ),
        )
        raw = ""
        try:
            for cand in (resp.candidates or []):
                for part in (cand.content.parts or []):
                    t = getattr(part, "text", None)
                    if t: raw += t
        except Exception:
            pass
        return raw

    try:
        raw = await asyncio.wait_for(asyncio.to_thread(_run_raw), timeout=180)
        tools = await asyncio.wait_for(asyncio.to_thread(_run), timeout=5)
        return {
            "company": company,
            "call_num": call_num,
            "raw_chars": len(raw),
            "raw_preview": raw[:2000],
            "tools_found": len(tools),
            "first_tool_keys": list(tools[0].keys()) if tools else [],
            "preview": tools[:3],
        }
    except asyncio.TimeoutError:
        return {"error": f"timeout after 180s on call {call_num}"}
    except Exception as e:
        return {"error": str(e)}


# ── GCC Intelligence Hub ──────────────────────────────────────────────────────

class GCCIntelRequest(BaseModel):
    company_name: str = Field(..., min_length=1)
    domain: str = Field(default="")
    location: str = Field(default="")
    target_vendor: str = Field(default="")
    focus_domains: list[str] = Field(default_factory=list)


@app.post("/api/gcc-intel")
async def gcc_intel(req: GCCIntelRequest):
    """SSE stream: two-phase GCC Intelligence Hub."""
    from gcc_pipeline import run_gcc_intelligence

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        try:
            async for event in run_gcc_intelligence(
                company_name=req.company_name,
                domain=req.domain,
                location=req.location,
                target_vendor=req.target_vendor,
                focus_domains=req.focus_domains or None,
            ):
                yield _sse(event)
        except Exception as e:
            logger.error(f"GCC Intel error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── GCC Discovery ────────────────────────────────────────────────────────────

class GCCDiscoverRequest(BaseModel):
    industry: str = Field(..., min_length=1)
    location: str = Field(default="")


@app.post("/api/gcc-discover")
async def gcc_discover(req: GCCDiscoverRequest):
    """SSE stream: discover companies with GCCs in a given industry/location."""
    from gcc_pipeline import run_gcc_discovery

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        try:
            async for event in run_gcc_discovery(
                industry=req.industry,
                location=req.location,
            ):
                yield _sse(event)
        except Exception as e:
            logger.error(f"GCC Discover error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── GCC Enrichment ────────────────────────────────────────────────────────────

class GCCEnrichCompany(BaseModel):
    company_name: str
    gcc_location: str = Field(default="")
    domain: str = Field(default="")


class GCCEnrichRequest(BaseModel):
    companies: list[GCCEnrichCompany] = Field(..., min_length=1)


@app.post("/api/gcc-enrich")
async def gcc_enrich(req: GCCEnrichRequest):
    """SSE stream: enrich each company with 6 GCC intelligence sections."""
    from gcc_pipeline import run_gcc_enrichment

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        gcc_results = []
        try:
            async for event in run_gcc_enrichment(
                companies=[c.model_dump() for c in req.companies],
            ):
                if event.get("type") == "gcc_location_result":
                    gcc_results.append(event.get("result"))
                elif event.get("type") == "complete" and event.get("run_id"):
                    from report_store import save_report
                    save_report(event["run_id"], "gcc_intelligence",
                               ", ".join(c.company_name for c in req.companies),
                               f"{event.get('total_companies', 0)} companies enriched", event.get("usage"),
                               data={"mode": "company", "query": ", ".join(c.company_name for c in req.companies),
                                     "results": gcc_results, "deepProfiles": {}})
                yield _sse(event)
        except Exception as e:
            logger.error(f"GCC Enrich error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── GCC Profile (Table 2) ────────────────────────────────────────────────────

class GCCProfileRequest(BaseModel):
    company_name: str = Field(..., min_length=1)
    gcc_location: str = Field(..., min_length=1)


@app.post("/api/gcc-profile")
async def gcc_profile(req: GCCProfileRequest):
    """SSE: generate 8-dimension operational profile (Table 2) for a specific GCC."""
    from gcc_pipeline import run_gcc_profile

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        try:
            async for event in run_gcc_profile(req.company_name, req.gcc_location):
                yield _sse(event)
        except Exception as e:
            logger.error(f"GCC Profile error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── GCC Design (Table 3) ──────────────────────────────────────────────────────

class GCCDesignRequest(BaseModel):
    company_name: str = Field(..., min_length=1)
    gcc_location: str = Field(..., min_length=1)


@app.post("/api/gcc-design")
async def gcc_design(req: GCCDesignRequest):
    """SSE: generate 3-pillar operational design profile (Table 3) for a specific GCC."""
    from gcc_pipeline import run_gcc_design

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        try:
            async for event in run_gcc_design(req.company_name, req.gcc_location):
                yield _sse(event)
        except Exception as e:
            logger.error(f"GCC Design error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── Aftermarket Deep Dive ─────────────────────────────────────────────────────

class AftermarketRequest(BaseModel):
    company_name: str = Field(..., min_length=1)
    domain: str = Field(default="")
    industry: str = Field(default="")
    competitors: str = Field(default="")
    target_vendor: str = Field(default="")
    sections_to_run: list[str] = Field(default_factory=list)  # empty = all sections
    existing_spend_rows: list[dict] = Field(default_factory=list)  # pass when regenerating readiness-only


@app.post("/api/aftermarket-dive")
async def aftermarket_dive(req: AftermarketRequest):
    """SSE stream: Aftermarket Deep Dive analysis."""
    from aftermarket_pipeline import run_aftermarket_deep_dive

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        try:
            from aftermarket_pipeline import ALL_SECTIONS
            sections = set(req.sections_to_run) & ALL_SECTIONS if req.sections_to_run else None
            async for event in run_aftermarket_deep_dive(
                company_name=req.company_name,
                domain=req.domain,
                industry=req.industry,
                competitors=req.competitors,
                target_vendor=req.target_vendor,
                sections_to_run=sections,
                existing_spend_rows=req.existing_spend_rows or [],
            ):
                if event.get("type") == "complete" and event.get("run_id"):
                    from report_store import save_report
                    save_report(event["run_id"], "aftermarket_intelligence", req.company_name,
                               f"{len(event.get('sections_ran', []))} section(s)", event.get("usage"),
                               data={"company": req.company_name, "domain": req.domain,
                                     "summary": f"{len(event.get('capabilities', []))} capabilities · {len(event.get('aggregate_spend', []))} spend categories",
                                     "capRows": event.get("capabilities", []),
                                     "spendRows": event.get("spend_modules", []),
                                     "aggRows": event.get("aggregate_spend", []),
                                     "spendDealRows": event.get("spend_deals", []),
                                     "readyRows": event.get("readiness", []),
                                     "compRows": event.get("competitors", [])})
                yield _sse(event)
        except Exception as e:
            logger.error(f"Aftermarket dive error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


@app.get("/api/debug-aftermarket-section")
async def debug_aftermarket_section(company: str = "Daimler Truck North America", section: str = "spend_module"):
    """Debug a specific aftermarket section — returns rows + raw Gemini response preview."""
    import re as _re, json as _json
    from aftermarket_pipeline import _spend_module_prompt, _readiness_tam_prompt
    from google import genai
    from google.genai import types
    import os

    GOOGLE_AI_KEY = os.getenv("GOOGLE_AI_API_KEY", "")
    prompts = {
        "spend_module": _spend_module_prompt(company, ""),
        "readiness": _readiness_tam_prompt(company, "", ""),
    }
    prompt = prompts.get(section)
    if not prompt:
        return {"error": f"Unknown section: {section}"}

    def _run():
        import re as _re, json as _json
        max_tok = 32768 if section == "readiness" else 16384
        client = genai.Client(api_key=GOOGLE_AI_KEY)
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.15,
                max_output_tokens=max_tok,
                tools=[types.Tool(google_search=types.GoogleSearch())],
            ),
        )
        parts_info = []
        text_parts = []
        for cand in (response.candidates or []):
            for part in (cand.content.parts or []):
                thought = getattr(part, "thought", None)
                txt = getattr(part, "text", "") or ""
                parts_info.append({"thought": thought, "text_len": len(txt)})
                if not thought and txt:
                    text_parts.append(txt)
        finish = getattr(response.candidates[0], "finish_reason", None) if response.candidates else None
        combined = "".join(text_parts)
        clean = _re.sub(r"```(?:json)?\s*", "", combined.strip())
        clean = _re.sub(r"```\s*$", "", clean, flags=_re.MULTILINE).strip()
        parse_err = None
        rows = []
        try:
            rows = _json.loads(clean)
        except Exception as e:
            parse_err = str(e)
            m = _re.search(r"\[.*\]", combined, _re.DOTALL)
            if m:
                try:
                    t2 = _re.sub(r",\s*([\]}])", r"\1", m.group(0))
                    rows = _json.loads(t2)
                    parse_err = None
                except Exception as e2:
                    parse_err = f"regex: {e2}"
        return {
            "rows_parsed": len(rows) if isinstance(rows, list) else 0,
            "parse_error": parse_err,
            "parts": parts_info,
            "finish_reason": str(finish),
            "combined_len": len(combined),
            "clean_head": clean[:300],
            "clean_tail": clean[-200:],
            "row_domains": [r.get("domain") for r in rows[:9]] if isinstance(rows, list) else [],
        }

    try:
        result = await asyncio.wait_for(asyncio.to_thread(_run), timeout=300)
        return {"company": company, "section": section, **result}
    except Exception as e:
        import traceback
        return {"error": str(e) or type(e).__name__, "tb": traceback.format_exc()[-300:]}


# ── Signal Intelligence ───────────────────────────────────────────────────────

class SignalCompanyInput(BaseModel):
    name: str = Field(..., min_length=1)
    domain: str = Field(default="")

class SignalIntelRequest(BaseModel):
    target_companies: list[SignalCompanyInput] = Field(..., min_length=1, max_length=100)
    user_company: str = Field(default="")
    user_domain: str = Field(default="")
    key_triggers: str = Field(default="")
    target_tech: str = Field(default="")
    lookback_days: int = Field(default=365, ge=7, le=1095)


@app.post("/api/signal-intel")
async def signal_intel(req: SignalIntelRequest):
    """SSE stream: buying signal intelligence for up to 100 target companies."""
    from signal_pipeline import run_signal_intelligence

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set."})
            return

        all_signals = []
        try:
            companies = [{"name": c.name, "domain": c.domain} for c in req.target_companies]
            async for event in run_signal_intelligence(
                target_companies=companies,
                user_company=req.user_company,
                user_domain=req.user_domain,
                key_triggers=req.key_triggers,
                target_tech=req.target_tech,
                lookback_days=req.lookback_days,
            ):
                if event.get("type") == "signal_row" and event.get("row"):
                    all_signals.append(event["row"])
                elif event.get("type") == "signals_ranked":
                    company = event.get("company")
                    all_signals = [r for r in all_signals if r.get("company") != company] + (event.get("rows") or [])
                elif event.get("type") == "complete" and event.get("run_id"):
                    from report_store import save_report
                    save_report(event["run_id"], "signal_intelligence",
                               ", ".join(c.name for c in req.target_companies),
                               f"{event.get('total', 0)} signals · {event.get('companies_done', 0)} companies",
                               event.get("usage"),
                               data={"companies": ", ".join(c.name for c in req.target_companies),
                                     "total": event.get("total", 0),
                                     "userCompany": req.user_company,
                                     "timeline": f"{req.lookback_days}d",
                                     "rows": all_signals})
                yield _sse(event)
        except Exception as e:
            logger.error(f"Signal Intel error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


# ── Competitive Intelligence ──────────────────────────────────────────────────

class CompetitiveDiscoverRequest(BaseModel):
    target_company: str = Field(..., min_length=1)
    target_domain: str = Field(default="")
    industry_context: str = Field(default="")
    technology_context: str = Field(default="")


class CompetitorInput(BaseModel):
    name: str = Field(..., min_length=1)
    domain: str = Field(default="")


class CompetitiveAnalyzeRequest(BaseModel):
    target_company: str = Field(..., min_length=1)
    target_domain: str = Field(default="")
    competitors: list[CompetitorInput] = Field(default_factory=list, max_length=5)
    enabled_modules: list[str] = Field(default_factory=list)
    benchmark_focus: list[str] = Field(default_factory=lambda: ["Overall Competitiveness"])
    industry_context: str = Field(default="")
    technology_context: str = Field(default="")


@app.post("/api/competitive/discover")
async def competitive_discover(req: CompetitiveDiscoverRequest):
    """Return 8-10 competitor suggestions for the target company."""
    if not os.getenv("GOOGLE_AI_API_KEY"):
        raise HTTPException(status_code=500, detail="GOOGLE_AI_API_KEY not set on server.")

    from competitive_pipeline import discover_competitors
    try:
        competitors = await asyncio.wait_for(
            discover_competitors(req.target_company, req.target_domain, req.industry_context, req.technology_context),
            timeout=120,
        )
        return {"competitors": competitors}
    except Exception as e:
        logger.error(f"Competitive discover error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/competitive/analyze")
async def competitive_analyze(req: CompetitiveAnalyzeRequest):
    """SSE stream: full competitive analysis across selected modules."""
    from competitive_pipeline import run_competitive_analysis, MODULES

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"

        if not os.getenv("GOOGLE_AI_API_KEY"):
            yield _sse({"type": "error", "message": "GOOGLE_AI_API_KEY not set on server."})
            return

        # Default to all modules if none specified
        enabled = [m for m in req.enabled_modules if m in MODULES] or list(MODULES.keys())
        # metrics is always first
        if "metrics" in enabled:
            enabled = ["metrics"] + [m for m in enabled if m != "metrics"]

        competitors = [{"name": c.name, "domain": c.domain} for c in req.competitors]

        benchmark_focus_str = ", ".join(req.benchmark_focus) if isinstance(req.benchmark_focus, list) else req.benchmark_focus

        comp_results = []
        comp_synthesis = ""
        try:
            async for event in run_competitive_analysis(
                target_company=req.target_company,
                target_domain=req.target_domain,
                competitors=competitors,
                enabled_modules=enabled,
                benchmark_focus=benchmark_focus_str,
                industry_context=req.industry_context,
                technology_context=req.technology_context,
            ):
                if event.get("type") == "company_result":
                    comp_results.append({"company": event.get("company"), "domain": event.get("domain"),
                                         "is_target": event.get("is_target"), "modules": event.get("modules") or []})
                elif event.get("type") == "synthesis":
                    comp_synthesis = event.get("text", "")
                elif event.get("type") == "complete" and event.get("run_id"):
                    from report_store import save_report
                    save_report(event["run_id"], "compkill", req.target_company,
                               f"{len(competitors)} competitors · {len(enabled)} modules", event.get("usage"),
                               data={"target": req.target_company, "competitors": [c["name"] for c in competitors],
                                     "modules": enabled, "benchmarkFoci": req.benchmark_focus,
                                     "industryContext": req.industry_context, "technologyContext": req.technology_context,
                                     "results": comp_results, "synthesis": comp_synthesis})
                yield _sse(event)
        except Exception as e:
            logger.error(f"Competitive analyze error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )



# ── Industry Deals ────────────────────────────────────────────────────────────

from industry_deals_pipeline import generate_company_list, search_industry_deals


class IndustryCompaniesRequest(BaseModel):
    industry: str = Field(..., min_length=1)
    geography: str = Field(default="")
    company_name: str = Field(default="")
    domain: str = Field(default="")
    focus_tech: str = Field(default="")


class IndustryDealsSearchRequest(BaseModel):
    companies: list[dict] = Field(default_factory=list)
    industry: str = Field(..., min_length=1)
    geography: str = Field(default="")
    renewal_timeframe: str = Field(default="1 year")
    focus_tech: str = Field(default="")


@app.get("/api/debug-industry-companies")
async def debug_industry_companies(industry: str = "Banking", geography: str = "France"):
    import json as _json
    from industry_deals_pipeline import _company_list_prompt, _gemini_sync, _parse_json
    prompt = _company_list_prompt(industry, geography)
    text = await asyncio.to_thread(_gemini_sync, prompt)
    start = text.find("[")
    end   = text.rfind("]")
    fragment = text[start:end+1] if (start != -1 and end > start) else ""
    try:
        direct = _json.loads(fragment)
        direct_ok = True; direct_err = None
    except Exception as e:
        direct = None; direct_ok = False; direct_err = str(e)
    parsed = _parse_json(text)
    return {
        "text_len": len(text), "text_tail": text[-100:],
        "bracket_start": start, "bracket_end": end,
        "fragment_len": len(fragment), "fragment_tail": fragment[-80:] if fragment else "",
        "direct_parse_ok": direct_ok, "direct_parse_err": direct_err,
        "parsed_type": str(type(parsed)), "parsed_len": len(parsed) if isinstance(parsed, list) else None,
    }


@app.post("/api/industry-companies")
async def industry_companies(req: IndustryCompaniesRequest):
    if not os.getenv("GOOGLE_AI_API_KEY"):
        raise HTTPException(status_code=500, detail="GOOGLE_AI_API_KEY not set on server.")
    try:
        companies = await asyncio.wait_for(
            asyncio.to_thread(
                generate_company_list,
                req.industry, req.geography, req.company_name, req.domain, req.focus_tech,
            ),
            timeout=120,
        )
    except asyncio.TimeoutError:
        raise HTTPException(status_code=504, detail="Company list generation timed out — try again.")
    except Exception as e:
        logger.error(f"industry_companies error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
    return {"companies": companies}


@app.post("/api/industry-deals-search")
async def industry_deals_search(req: IndustryDealsSearchRequest):
    if not os.getenv("GOOGLE_AI_API_KEY"):
        raise HTTPException(status_code=500, detail="GOOGLE_AI_API_KEY not set on server.")
    if not req.companies:
        raise HTTPException(status_code=400, detail="No companies provided.")

    async def _generate():
        def _sse(obj: dict) -> str:
            return f"data: {json.dumps(obj)}\n\n"
        renewal_deals = []
        all_deals = []
        try:
            async for event in search_industry_deals(
                req.companies, req.industry, req.geography,
                req.renewal_timeframe, req.focus_tech,
            ):
                if event.get("type") == "deal" and event.get("deal"):
                    deal = event["deal"]
                    all_deals.append(deal)
                    if deal.get("in_renewal_window"):
                        renewal_deals.append(deal)
                elif event.get("type") == "complete" and event.get("run_id"):
                    from report_store import save_report
                    save_report(event["run_id"], "it_deals_by_industry", f"{req.industry} · {req.geography}",
                               f"{event.get('processed', 0)}/{event.get('total', 0)} companies searched", event.get("usage"),
                               data={"industry": req.industry, "geography": req.geography,
                                     "renewal_timeframe": req.renewal_timeframe, "focus_tech": req.focus_tech,
                                     "companies": [c.get("company_name") for c in req.companies],
                                     "renewalDeals": renewal_deals, "allDeals": all_deals})
                yield _sse(event)
        except Exception as e:
            logger.error(f"Industry deals search error: {e}", exc_info=True)
            yield _sse({"type": "error", "message": str(e)})

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=4001, reload=True)
