services:
  - type: web
    name: it-deals-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: SERPER_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: JINA_KEY
        sync: false
      - key: GOOGLE_PSE_KEY
        sync: false
      - key: GOOGLE_PSE_CX
        sync: false
      - key: SCRAPEDO_KEY
        sync: false
      - key: PARALLEL_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
